services:
  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gym-network

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - gym-network

  gym-main-service:
    build: ./gym-main-service
    container_name: gym-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_ENABLED=false
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    depends_on:
      - activemq
    networks:
      - gym-network

  trainer-workload-service:
    build: ./trainer-workload-service
    container_name: trainer-workload
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/trainer-workload-db
    depends_on:
      - activemq
      - mongodb
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge